# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/75d9029b-b2a0-4f84-8907-1462cea199f5";
    fsType = "ext4";
  };

  fileSystems."/boot" = { 
    device = "/dev/nvme0n1p1";
    fsType = "vfat";
    options = [ "fmask=0177" "dmask=0077" ];
  };

  swapDevices = [ 
    { device = "/dev/disk/by-uuid/90d11698-448e-4013-bac7-94c34d25d76a"; }
  ];
  
  fileSystems."/run/media/daniil/D" = {
    # device = "/dev/disk/by-uuid/e728007a-6d2a-4e2f-ad14-3593d79b86b2";
    device = "/dev/sda1";
    fsType = "ext4";
    options = [ "users" "nofail" "exec" "uid=1000" "rw" ];
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
