# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAFAFA
background         #2A2A2A
cursor             #929292

active_tab_foreground     #2A2A2A
active_tab_background     #FAFAFA
inactive_tab_foreground   #FAFAFA
inactive_tab_background   #2A2A2A

active_border_color   #FAFAFA
inactive_border_color #2A2A2A
bell_border_color     #201F1F

color0      #4F4F4F
color1		#201F1F
color2		#202020
color3		#232323
color4		#5D5D5D
color5		#747474
color6		#B4B4B4
color7		#EFEFEF
color8		#A7A7A7
color9		#2A2A2A
color10		#2A2A2A
color11		#2F2F2F
color12		#7C7C7C
color13		#9B9B9B
color14		#F0F0F0
color15		#EFEFEF
