# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2A2A)
$foreground = rgb(FAFAFA)
$color0 = rgb(4F4F4F)
$color1 = rgb(201F1F)
$color2 = rgb(202020)
$color3 = rgb(232323)
$color4 = rgb(5D5D5D)
$color5 = rgb(747474)
$color6 = rgb(B4B4B4)
$color7 = rgb(EFEFEF)
$color8 = rgb(A7A7A7)
$color9 = rgb(2A2A2A)
$color10 = rgb(2A2A2A)
$color11 = rgb(2F2F2F)
$color12 = rgb(7C7C7C)
$color13 = rgb(9B9B9B)
$color14 = rgb(F0F0F0)
$color15 = rgb(EFEFEF)
